# UMRT
# Rover Low

/**/*:
  ros__parameters:
    network_interface: "network_bridge::UdpInterface"

    UdpInterface:
      local_address: "192.168.1.2"
      receive_port: 5012  # lo rover port
      remote_address: "192.168.1.1"
      send_port: 5011     # lo base port
  
  
    # default_rate: 100.0
    # default_zstd_level: 3
    publish_stale_data: False

    #---------------------------------------------
    # config local topics to subscribe (outgoing)
    #---------------------------------------------

    topics:
      - "/telemetry"
    subscribe_namespace: "/bs_lo"  # prefix of local topics to subscribe to outgoing
    
    
    #---------------------------------------------
    # config incoming topics to publish (incoming)
    #---------------------------------------------
    publish_namespace: "/bs_lo"    # add prefix of incoming publishing topics