# UMRT
# Base Station High

/**/*:
  ros__parameters:
    network_interface: "network_bridge::UdpInterface"

    UdpInterface:
      local_address: "10.0.20.57"
      receive_port: 5257  # hi base port
      remote_address: "10.0.20.59"
      send_port: 5259     # hi rover port
  
  
    default_rate: 100.0
    default_zstd_level: 3
    publish_stale_data: False

