name: foxglove_bridge_stack

services:
  foxglove_bridge:
    image: bridge_test:v1
    container_name: foxglove_bridge
    restart: unless-stopped
    command: ros2 launch foxglove_bridge foxglove_bridge+launch.xml
    ports:
      # Exposes container's 8765 to host's 8765
      - "127.0.0.1:8765:8765" 
#    environment:
#      ROS_DOMAIN_ID: "1"
    networks:
      bridge_hi:
        ipv4_address: 10.0.20.49

networks:
  bridge_hi:
    external: true