name: rover_hi_stack

services:
  bridge_rover:
    image: "${BRIDGE_ROVER_IMAGE:-ghcr.io/umroboticsteam/umrt-build:comms-zenoh-bridge}"
    container_name: bridge_rover_hi
    stdin_open: true
    tty: true
    init: true
    environment:
      ROS_DOMAIN_ID: "2"
      ROS_LOCALHOST_ONLY: "0"
      RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
      BRIDGE_WORKSPACE: "/workspace/bridge_test"
#    devices:
#      - "/dev/video0:/dev/video0" # expose USB cam testing
    volumes:
      - "${REPO_DIR:-..}:/workspace/bridge_test"
    command:
      - bash
      - -lc
      - exec /workspace/bridge_test/scripts/run_zenoh_stack.sh rover-hi
    networks:
      bridge_hi:
        ipv4_address: 10.0.20.59

networks:
  bridge_hi:
    external: true
