name: bridge_lo_test

services:
  bridge_rover:
    build:
      context: ..
      dockerfile: Dockerfile
    image: bridge_test:v1
    container_name: bridge_rover_lo
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    entrypoint: ["/usr/local/bin/network_policy.sh"]
    command: ["bash"]
    environment:
      RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
      FASTDDS_DEFAULT_PROFILES_FILE: "/dds-configs/fastdds-rover-lo.xml"
      ROUTE_POLICY: "preserve"
    volumes:
      - ../container_scripts/network_policy.sh:/usr/local/bin/network_policy.sh:ro
      - ../dds-configs:/dds-configs:ro
#    devices:
#      - "/dev/video0:/dev/video0" # expose USB cam testing
    networks:
      bridge_lo:
        ipv4_address: 10.0.10.59

networks:
  bridge_lo:
    external: true
