services:
  bridge_rover:
    image: bridge_test:v1
    container_name: bridge_rover
    stdin_open: true
    tty: true
    environment:
      ROS_DOMAIN_ID: "2"
#    devices:
#      - "/dev/video0:/dev/video0" # expose USB cam testing
    volumes:
      - ./config/rover-hi.yaml:/opt/ros/humble/share/network_bridge/config/rover-hi.yaml:ro
      - ./config/rover-lo.yaml:/opt/ros/humble/share/network_bridge/config/rover-lo.yaml:ro
      - ./config/rover.launch.py:/opt/ros/humble/share/network_bridge/launch/rover.launch.py:ro
    command:
      - bash
      - -lc
      - source /opt/ros/humble/setup.bash && ros2 launch network_bridge rover.launch.py
    networks:
      bridge_lo:
        ipv4_address: 10.0.10.59
      bridge_hi:
        ipv4_address: 10.0.20.59

networks:
  bridge_lo:
    external: true
  bridge_hi:
    external: true
