# UMRT
# Base Station High

/**/*:
  ros__parameters:
    network_interface: "network_bridge::UdpInterface"

    UdpInterface:
      local_address: "192.168.2.1"
      receive_port: 5021  # hi base port
      remote_address: "192.168.2.2"
      send_port: 5022     # hi rover port
  
  
    # default_rate: 100.0
    # default_zstd_level: 3
    publish_stale_data: False

    #---------------------------------------------
    # config local topics to subscribe (outgoing)
    #---------------------------------------------

    # topics:
    #   - "/telemetry"
    # subscribe_namespace: "/rv_hi"  # prefix of local topics to subscribe to outgoing
    
    
    #---------------------------------------------
    # config incoming topics to publish (incoming)
    #---------------------------------------------
    publish_namespace: "/rv_hi"    # add prefix of incoming publishing topics